# Operating system (build VM template)
os: Visual Studio 2015

shallow_clone: true

platform: x64

configuration:
  - Debug
  - Release

# clone directory
#clone_folder: c:\code\jonoondb

# scripts to run before build
before_build:
  - cmake -G "Visual Studio 14 Win64" -Dgtest_force_shared_crt=ON -DBOOST_ROOT=C:\Libraries\boost_1_60_0
  
build:
  parallel: true             # enable MSBuild parallel builds
  project: JonoonDB.sln      # path to Visual Studio solution or project
  
test_script:
  - ctest -V
  
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
