# Operating system (build VM template)
os: Visual Studio 2019

shallow_clone: true

platform: x64

configuration:
  - Debug
  - Release

# scripts to run before build
before_build:
- cmake . -G "Visual Studio 16 2019" -A x64 -Dgtest_force_shared_crt=ON -DBOOST_ROOT=C:\Libraries\boost_1_73_0 -DBOOST_LIBRARYDIR=C:\Libraries\boost_1_73_0\lib64-msvc-16.0
  
build:
  parallel: true             # enable MSBuild parallel builds
  project: JonoonDB.sln      # path to Visual Studio solution or project
  
test_script:
  - ctest -V
  
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
